// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_ZARsoi6Z5oQMBWgPBRgzdd25R4KvfPo',
    appId: '1:11946535479:web:1675918f8b9fdad64e2db2',
    messagingSenderId: '11946535479',
    projectId: 'shaikhsanad-59127',
    authDomain: 'shaikhsanad-59127.firebaseapp.com',
    storageBucket: 'shaikhsanad-59127.firebasestorage.app',
    measurementId: 'G-D389CTGP90',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaB32th3N2d-BelPb3vkbpZqAuXHGuMY4',
    appId: '1:11946535479:android:0b27859ab6ee79884e2db2',
    messagingSenderId: '11946535479',
    projectId: 'shaikhsanad-59127',
    storageBucket: 'shaikhsanad-59127.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaoC8FBkjSU1zByTsYcuhUcbEfQWP3JLw',
    appId: '1:11946535479:ios:621195365f6101e94e2db2',
    messagingSenderId: '11946535479',
    projectId: 'shaikhsanad-59127',
    storageBucket: 'shaikhsanad-59127.firebasestorage.app',
    iosBundleId: 'com.alialrikabi313.istftaatsanad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaoC8FBkjSU1zByTsYcuhUcbEfQWP3JLw',
    appId: '1:11946535479:ios:621195365f6101e94e2db2',
    messagingSenderId: '11946535479',
    projectId: 'shaikhsanad-59127',
    storageBucket: 'shaikhsanad-59127.firebasestorage.app',
    iosBundleId: 'com.alialrikabi313.istftaatsanad',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_ZARsoi6Z5oQMBWgPBRgzdd25R4KvfPo',
    appId: '1:11946535479:web:3cdb19d9028493bb4e2db2',
    messagingSenderId: '11946535479',
    projectId: 'shaikhsanad-59127',
    authDomain: 'shaikhsanad-59127.firebaseapp.com',
    storageBucket: 'shaikhsanad-59127.firebasestorage.app',
    measurementId: 'G-2MX2PX649W',
  );
}
